
services: 
  db: 
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    container_name: tiendadb
    volumes:
      - ./postgres:/var/lib/postgresql/data